#!/usr/bin/env bash
set -e

adduser --quiet --disabled-password --home $SFTP_HOME --shell /bin/false --ingroup sftp  --gecos "SFTP User"  $SFTP_USER
echo "$SFTP_USER:$SFTP_PWD" | chpasswd

# start SSH daemon
/usr/sbin/sshd -D -e

